name: Auto-Generate Report
on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9AM
  workflow_dispatch:      # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install firebase-admin

      - name: Generate report
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node firebase-report.js

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: firebase-report
          path: report.html