name: Daily Gmail Report
on:
  schedule:
    - cron: '0 9 * * *'  # 9AM daily
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install firebase-admin date-fns nodemailer
      
      - name: Run and email report
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          BOSS_EMAIL: ${{ secrets.BOSS_EMAIL }}
        run: node firebase-report.js
