name: Daily Production Report
on:
  schedule:
    - cron: '30 2 * * *'  # 8:00 AM IST (2:30 UTC)
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install firebase-admin nodemailer
      - run: node firebase-report.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          BOSS_EMAIL: ${{ secrets.BOSS_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
